name: hank_talker_mobile
description: Hand Talker
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  awesome_bottom_bar: ^1.2.4
  bloc: ^8.1.2
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_phosphor_icons: ^0.0.1+6
  flutter_svg: ^2.0.9
  http: ^1.1.0
  intl: ^0.18.0
  lottie: ^2.6.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  android_adaptive_icon: true
  image_path: "assets/images/ic_launcher-playstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#FFFFFF"
  #background_image: "assets/background.png"

  android_12:
    image: assets/images/splash_screen.png

    # Splash screen background color.
    color: "#FFFFFF"
    # App icon background color.
    icon_background_color: "#FFFFFF"

    image_dark: assets/images/splash_screen.png
    color_dark: "#FFFFFF"
    #icon_background_color_dark: "#eeeeee"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/images/contributors/
    - assets/images/backgrounds/
