name: hank_talker_mobile
description: Hand Talker
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  awesome_bottom_bar: ^1.2.4
  bloc: ^8.1.2
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_phosphor_icons: ^0.0.1+6
  http: ^1.1.0
  intl: ^0.18.0
  lottie: ^2.6.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo_HT_solo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/animations/
